### ISSUE TITLE
set destPath in config

### ISSUE THREAD

**Issue by fullstackwebdev** [deebloo/generator-angular-blueprint#21] opened 2016-02-18 07:15 UTC
Hi,

for some reason, when I run 'yo angular-blueprint:XXXX name' I get prompted with a undefined in the default destination path:

```
$ yo angular-blueprint:route newPage
? Where should I generate "new-page"? (undefinednew-page) 
```

I tried to add "destDir" in .yo-rc : 

```
$ cat .yo-rc.json 
{
  "generator-angular-blueprint": {
    "appName": "blueprint",
    "destPath": "MYDIRECTORY",
  },
... 
```

but it still couldn't find it.  The line of code is:
https://github.com/deebloo/generator-angular-blueprint/blob/master/lib/prompt-install-path.js#L7

But I am unable to find how to set destPath , assuming that will fix my problem. Can you shed some light on this? Great project.  

Also another question, can I do more then one blueprint override for routes? Like a Panel1.html and Panel2.html?

**Comment by fullstackwebdev** [comment] 2016-02-18 07:15
Oh also I tried adding the variable in blueprint/blueprint.json as well --  is there any documentation for what goes into blueprint.json?

**Comment by deebloo** [comment] 2016-02-18 12:54
are you running on windows or mac?

**Comment by fullstackwebdev** [comment] 2016-02-18 13:24
Linux ubuntu 14.04 lts. Thanks

**Comment by deebloo** [comment] 2016-02-18 16:48
ill look into it and get back to you

**Comment by deebloo** [comment] 2016-02-22 01:17
Sorry for the delayed response. Work has been keeping me away form side projects. Also please feel free to submit a pr if you find out what the issue is.

**Comment by deebloo** [comment] 2016-03-18 13:51
hey. sorry again for being so unresponsive. Ive replicated the bug and should put a fix out soon

**Comment by deebloo** [comment] 2016-03-18 14:10
@fullstackwebdev I just pushed a fix into master. so check it out there and see if that helps! im testing some more before i publish a new release since there is a lot of stuff in it

**Closed as completed** 2016-06-22 16:19 UTC
